server:
  port: 8082
  
spring:
  kafka:
    bootstrap-servers: localhost:9092

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
