services:
  services:
    user-service:
      url: http://localhost:8081
    notification-service:
      url: http://localhost:8082

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 100
        waitDurationInOpenState: 10000
        slidingWindowSize: 2
        minimumNumberOfCalls: 2
    instances:
      user-service:
        base-config: default
      notification-service:
        base-config: default

spring:
  webflux:
    client:
      response-timeout: 30s

server:
  port: 8084
