services:
  services:
    user-service:
      url: http://localhost:8081
    notification-service:
      url: http://localhost:8082

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        sliding-window-size: 5
        minimum-number-of-calls: 2
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: COUNT_BASED
        # Отключаем таймауты для тестирования
        slow-call-duration-threshold: 60s
        # Игнорируем только 4xx ошибки
        ignore-exceptions:
          - "org.springframework.web.reactive.function.client.WebClientResponseException\$NotFound"
          - "org.springframework.web.reactive.function.client.WebClientResponseException\$BadRequest"

logging:
  level:
    org.springframework.cloud.circuitbreaker: DEBUG
    dev.dmv04.circuitbreaker: DEBUG

spring:
  webflux:
    client:
      response-timeout: 10s

server:
  port: 8084
