services:
  services:
    user-service:
      url: http://localhost:8081
    notification-service:
      url: http://localhost:8082

spring:
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true

spring:
  webflux:
    client:
      response-timeout: 10s

server:
  port: 8084
