services:
  services:
    user-service:
      url: http://localhost:8081
    notification-service:
      url: http://localhost:8082

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        slow-call-duration-threshold: 0
        
    instances:
      user-service:
        base-config: default
      notification-service:
        base-config: default

spring:
  webflux:
    client:
      response-timeout: 30s

server:
  port: 8084
