spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_service_db 
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092

  jackson:
    serialization:
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      email-send:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3

server:
  port: 8081
